#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
name="Best School"
i=0
while [ $i -lt 10 ]
do
    if [ $i == 9 ]
    then
        echo "Hi"
    fi
    echo "$name"
    ((i++))
done
