#!/usr/bin/env bash
# This script is displaying num from 1 to 20 times, 4th bad luck from China, 9th bad luck from Japan, and 17th bad luck from Italy
i=1
while [ $i -le 20 ]
do
    echo "$i"
    case $i in
    4)
        echo "bad luck from China"
    ;;
    9)
    echo "bad luck from Japan"
    ;;
    17)
    echo "bad luck from Italy"
    ;;
    esac
    ((i++))
done
